import dotenv from "dotenv";
import { BLOODLINES_ASSISTANT_PROTOCOL } from "./assistantProtocol";
import { BLOODLINES_AI_GOVERNANCE } from "./aiGovernance";
import { buildRepositoryContext, buildGovernanceRepositoryContext } from "./repositoryContext";

dotenv.config({ override: true });

const DEFAULT_MAX_TOKENS = 1600;
const REPAIR_MAX_TOKENS = 2400;
const GOVERNANCE_MAX_TOKENS = 700;
const OPENROUTER_FREE_MODEL = "openrouter/free";
const GROQ_MODEL = process.env.GROQ_MODEL ?? "groq/compound";
const GROQ_FALLBACK_MODEL = process.env.GROQ_FALLBACK_MODEL ?? "groq/compound-mini";
const OPENROUTER_MODEL = process.env.OPENROUTER_MODEL ?? OPENROUTER_FREE_MODEL;
const GEMINI_MODEL = process.env.GEMINI_MODEL ?? "gemini-3.1-flash-lite-preview";
const CEREBRAS_MODEL = process.env.CEREBRAS_MODEL ?? "gpt-oss-120b";
interface ProviderBudget { remainingTokens?: number; remainingRequests?: number; resetTokensAt?: number; resetRequestsAt?: number; retryAfterAt?: number; }
const groqBudget: ProviderBudget = {}, openRouterBudget: ProviderBudget = {}, geminiBudget: ProviderBudget = {}, cerebrasBudget: ProviderBudget = {};
function buildMessages(prompt: string, systemPrompt: string, includeRepositoryContext = true) { const resolvedSystemPrompt = `${BLOODLINES_AI_GOVERNANCE}\n\n${BLOODLINES_ASSISTANT_PROTOCOL}\n\nASSIGNED ASSISTANT ROLE\n\n${systemPrompt}`; const repositoryContext = includeRepositoryContext ? buildRepositoryContext(prompt) : ""; return [{ role: "system", content: resolvedSystemPrompt }, { role: "user", content: repositoryContext ? `${prompt}\n\n${repositoryContext}` : prompt }]; }
function estimateTokens(messages: Array<{ role: string; content: string }>, maxTokens: number) { return Math.ceil(messages.reduce((total, message) => total + message.content.length, 0) / 4) + maxTokens; }
function updateBudget(headers: Headers, budget: ProviderBudget) { const remainingTokens = Number(headers.get("x-ratelimit-remaining-tokens")); const remainingRequests = Number(headers.get("x-ratelimit-remaining-requests")); if (Number.isFinite(remainingTokens)) budget.remainingTokens = remainingTokens; if (Number.isFinite(remainingRequests)) budget.remainingRequests = remainingRequests; const retryAfter = Number(headers.get("retry-after")); if (Number.isFinite(retryAfter)) budget.retryAfterAt = Date.now() + retryAfter * 1000; const tokenReset = headers.get("x-ratelimit-reset-tokens"); const requestReset = headers.get("x-ratelimit-reset-requests"); if (tokenReset) budget.resetTokensAt = Date.now() + parseDurationMs(tokenReset); if (requestReset) budget.resetRequestsAt = Date.now() + parseDurationMs(requestReset); }
function parseDurationMs(value: string) { const match = value.match(/(?:(\d+(?:\.\d+)?)h)?\s*(?:(\d+(?:\.\d+)?)m)?\s*(?:(\d+(?:\.\d+)?)s)?/i); if (!match) return 0; return Number(match[1] ?? 0) * 3600000 + Number(match[2] ?? 0) * 60000 + Number(match[3] ?? 0) * 1000; }
function providerCanHandle(budget: ProviderBudget, estimatedTokens: number) { const now = Date.now(); if (budget.retryAfterAt && budget.retryAfterAt > now) return false; if (budget.remainingRequests !== undefined && budget.remainingRequests <= 0) return false; if (budget.remainingTokens !== undefined && budget.remainingTokens < estimatedTokens) return false; return true; }
function safeProviderError(data: unknown) { if (!data || typeof data !== "object") return "unknown provider error"; const record = data as { error?: { message?: unknown; code?: unknown } }; const message = typeof record.error?.message === "string" ? record.error.message : "unknown provider error"; const code = record.error?.code !== undefined ? String(record.error.code) : "unknown"; return `${code}: ${message}`.slice(0, 500); }
function getProviderKey(name: "GROQ_API_KEY" | "OPENROUTER_API_KEY" | "GEMINI_API_KEY" | "CEREBRAS_API_KEY") { const value = process.env[name]?.trim(); if (!value) return undefined; if (/\s/.test(value) || /^(set|export)\s+/i.test(value)) throw new Error(`${name} is malformed; expected one API key on a single line`); return value; }
async function callGroq(key: string, model: string, messages: Array<{ role: string; content: string }>, maxTokens: number) { const response = await fetch("https://api.groq.com/openai/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model, max_tokens: maxTokens, messages }) }); updateBudget(response.headers, groqBudget); const data = await response.json(); if (!response.ok) throw new Error(`Groq request failed (${response.status}) [${model}]: ${safeProviderError(data)}`); const content = data?.choices?.[0]?.message?.content; if (typeof content !== "string" || !content.trim()) throw new Error(`Groq returned no usable content [${model}]`); return content; }
async function callOpenRouter(key: string, messages: Array<{ role: string; content: string }>, maxTokens: number) { const response = await fetch("https://openrouter.ai/api/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json", "HTTP-Referer": "https://github.com/Myztikal125/BLOODLINES", "X-Title": "BLOODLINES AI" }, body: JSON.stringify({ model: OPENROUTER_MODEL, max_tokens: maxTokens, messages }) }); updateBudget(response.headers, openRouterBudget); const data = await response.json(); if (!response.ok) throw new Error(`OpenRouter request failed (${response.status}) [${OPENROUTER_MODEL}]: ${safeProviderError(data)}`); const content = data?.choices?.[0]?.message?.content; if (typeof content !== "string" || !content.trim()) throw new Error("OpenRouter returned no usable content"); return content; }
async function callGemini(key: string, messages: Array<{ role: string; content: string }>, maxTokens: number) { const systemMessage = messages.find(message => message.role === "system")?.content ?? ""; const contents = messages.filter(message => message.role !== "system").map(message => ({ role: "user", parts: [{ text: message.content }] })); const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(GEMINI_MODEL)}:generateContent?key=${encodeURIComponent(key)}`; const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ systemInstruction: { parts: [{ text: systemMessage }] }, contents, generationConfig: { maxOutputTokens: maxTokens } }) }); updateBudget(response.headers, geminiBudget); const data = await response.json(); if (!response.ok) throw new Error(`Gemini request failed (${response.status}) [${GEMINI_MODEL}]: ${safeProviderError(data)}`); const content = data?.candidates?.[0]?.content?.parts?.map((part: { text?: unknown }) => part.text).filter((text: unknown): text is string => typeof text === "string").join(""); if (!content?.trim()) throw new Error(`Gemini returned no usable content [${GEMINI_MODEL}]`); return content; }
async function callCerebras(key: string, messages: Array<{ role: string; content: string }>, maxTokens: number) { const response = await fetch("https://api.cerebras.ai/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: CEREBRAS_MODEL, max_tokens: maxTokens, messages }) }); updateBudget(response.headers, cerebrasBudget); const data = await response.json(); if (!response.ok) throw new Error(`Cerebras request failed (${response.status}) [${CEREBRAS_MODEL}]: ${safeProviderError(data)}`); const content = data?.choices?.[0]?.message?.content; if (typeof content !== "string" || !content.trim()) throw new Error(`Cerebras returned no usable content [${CEREBRAS_MODEL}]`); return content; }
function isRepairRequest(prompt: string, systemPrompt: string) { return /repair|self-repair|typescript errors|compiler errors|tsc --noEmit/i.test(`${prompt}\n${systemPrompt}`); }
function isImplementationReport(prompt: string) { return /^BLOODLINES IMPLEMENTATION REPORT(?: REVISION)?/i.test(prompt); }
function isGovernanceAssistant(systemPrompt: string) { return /lead designer|report auditor|implementation assistant/i.test(systemPrompt); }
function buildCompactGovernanceContext(prompt: string, systemPrompt: string, includeRepositoryContext: boolean) { if (!includeRepositoryContext) return ""; if (isImplementationReport(prompt)) return buildRepositoryContext(prompt); if (isGovernanceAssistant(systemPrompt)) return buildGovernanceRepositoryContext(prompt).slice(0,3500); return buildRepositoryContext(prompt); }
export async function askAI(prompt: string, maxTokensOrSystemPrompt: number | string = DEFAULT_MAX_TOKENS, systemPrompt?: string, includeRepositoryContext = true) { const requestedMaxTokens = typeof maxTokensOrSystemPrompt === "number" ? maxTokensOrSystemPrompt : DEFAULT_MAX_TOKENS; const assistantSystemPrompt = systemPrompt ?? (typeof maxTokensOrSystemPrompt === "string" ? maxTokensOrSystemPrompt : "You are the BLOODLINES Research Assistant. Provide structured RPG research notes."); const governance = isGovernanceAssistant(assistantSystemPrompt); const maxTokens = governance ? GOVERNANCE_MAX_TOKENS : isRepairRequest(prompt, assistantSystemPrompt) ? Math.min(requestedMaxTokens, REPAIR_MAX_TOKENS) : requestedMaxTokens; const repositoryContext = buildCompactGovernanceContext(prompt, assistantSystemPrompt, includeRepositoryContext); const messages = buildMessages(prompt, assistantSystemPrompt, Boolean(repositoryContext)); if (repositoryContext) messages[1].content = `${prompt}\n\n${repositoryContext}`; const estimatedTokens = estimateTokens(messages, maxTokens); const failures: string[] = []; let groqKey: string | undefined, openRouterKey: string | undefined, geminiKey: string | undefined, cerebrasKey: string | undefined; try { groqKey = getProviderKey("GROQ_API_KEY"); } catch (error) { failures.push(error instanceof Error ? `Groq: ${error.message}` : "Groq: malformed API key"); } try { openRouterKey = getProviderKey("OPENROUTER_API_KEY"); } catch (error) { failures.push(error instanceof Error ? `OpenRouter: ${error.message}` : "OpenRouter: malformed API key"); } try { geminiKey = getProviderKey("GEMINI_API_KEY"); } catch (error) { failures.push(error instanceof Error ? `Gemini: ${error.message}` : "Gemini: malformed API key"); } try { cerebrasKey = getProviderKey("CEREBRAS_API_KEY"); } catch (error) { failures.push(error instanceof Error ? `Cerebras: ${error.message}` : "Cerebras: malformed API key"); }
  if (cerebrasKey && providerCanHandle(cerebrasBudget, estimatedTokens)) { try { return await callCerebras(cerebrasKey, messages, maxTokens); } catch (error) { failures.push(error instanceof Error ? error.message : "Cerebras: unknown error"); } } else if (!cerebrasKey) failures.push("Cerebras: CEREBRAS_API_KEY is not available to the Node process"); else failures.push("Cerebras: unavailable based on known rate limits");
  if (openRouterKey && providerCanHandle(openRouterBudget, estimatedTokens)) { try { return await callOpenRouter(openRouterKey, messages, maxTokens); } catch (error) { failures.push(error instanceof Error ? error.message : "OpenRouter: unknown error"); } } else if (!openRouterKey) failures.push("OpenRouter: OPENROUTER_API_KEY is not available to the Node process"); else failures.push("OpenRouter: unavailable based on known rate limits");
  if (groqKey) { for (const model of [GROQ_MODEL, GROQ_FALLBACK_MODEL].filter((model, index, models) => models.indexOf(model) === index)) { if (!providerCanHandle(groqBudget, estimatedTokens)) { failures.push(`Groq ${model}: unavailable based on known rate limits`); continue; } try { return await callGroq(groqKey, model, messages, maxTokens); } catch (error) { failures.push(error instanceof Error ? error.message : `Groq ${model}: unknown error`); } } } else failures.push("Groq: GROQ_API_KEY is not available to the Node process");
  if (geminiKey && providerCanHandle(geminiBudget, estimatedTokens)) { try { return await callGemini(geminiKey, messages, maxTokens); } catch (error) { failures.push(error instanceof Error ? error.message : "Gemini: unknown error"); } } else if (!geminiKey) failures.push("Gemini: GEMINI_API_KEY is not available to the Node process"); else failures.push("Gemini: unavailable based on known rate limits");
  throw new Error(`No AI provider could handle this request (estimated ${estimatedTokens} tokens).\n${failures.join("\n")}`);
}
